version: '3.7'
services:
  web-text-clipper-dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ../../src:/usr/app/src
    ports:
      - "3000:3000"
    tty: true
