version: '3.7'
services:
  web-text-clipper-dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - /c/chrome-extension:/work
    ports:
      - "3000:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPROLLING=true