FROM node:16.13.0
WORKDIR /src
ENV PATH /src/node_modules/.bin:$PATH
COPY package.json yarn.lock ./
RUN set -ex \
  && apt update && apt install -y libssl-dev openssl ssl-cert \
  && yarn install
COPY . .
EXPOSE 3000